#!/bin/sh

convert \
	-verbose \
	-trim \
	-density 150 \
	$1 \
	-quality 100 \
	-sharpen 0x1.0 \
	page.png

for f in page-*.png; do
	convert $f -background white -flatten -alpha off $f.out
	convert -quality 100 -crop 1240x554+0+30 $f.out $f.1
	convert -quality 100 -crop 1240x554+0+584 $f.out $f.2
	i=$(identify -format %[standard-deviation] $f.2 | cut -d"." -f1)
	if [ "0" == "$i" ]; then
		rm $f.2
	else
		convert -quality 100 -crop 1240x554+0+1138 $f.out $f.3
		i=$(identify -format %[standard-deviation] $f.3 | cut -d"." -f1)
		echo --------------$i----------------
		if [ "0" == "$i" ]; then
			rm $f.3
		fi
	fi
	rm $f.out
done

convert page-*.png.* -page A4+0+270 etykieta-do-druku.pdf
